# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20160628_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_md',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
