# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_article_content_md'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_md',
        ),
    ]
