# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-17 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_remove_article_content_md'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.IntegerField(default=1),
        ),
    ]
