# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-30 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('python', 'python'), ('notice', 'notice'), ('etc', 'etc')], default='etc', max_length=10),
        ),
    ]
