# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-25 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20170130_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
