# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-25 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20170225_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('python', 'python'), ('vue', 'vue'), ('notice', 'notice'), ('etc', 'etc')], default='etc', max_length=10),
        ),
    ]
