# Generated by Django 2.0 on 2018-06-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_auto_20180521_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('python', 'python'), ('vue', 'vue'), ('notice', 'notice'), ('etc', 'etc'), ('java', 'java'), ('docker', 'docker'), ('js', 'js')], default='etc', max_length=10),
        ),
    ]
